### ISSUE TITLE
Makefile changes

### ISSUE THREAD

**Issue by tssva** [jtgans/c128-tanks#1]
Are you open to pull requests for this project? I created a branch with a couple of changes to the makefiles which might remove some points of friction for those using this along with your videos for an intro to C128 programming. 

- Added support for building on Windows using the mingw32-make port of Gnu Make. Tested on Ubuntu 20.04 to insure changes didn't break building in posix environments.
- Removed sdl flags from 'test' target. Using the sdl flags causes the 'test' target to fail when using GTK3 versions of vice. Many Linux distro package manager versions (Ubuntu and Fedora for example), Homebrew on macOS and the Windows version are now GTK3 builds.

**Comment by jtgans** [comment]
Sure, I'm definitely up for PRs. Feel free to send one along! Apologies for not getting back to you sooner. The notifications for this hit my work address, not my personal one.
