### ISSUE TITLE
basic7: bload vs load

### ISSUE THREAD

**Issue by polluks** [jtgans/c128-tanks#2]
why?
![vice-screen-2023090401055977](https://github.com/jtgans/c128-tanks/assets/4707573/17bba7ac-e838-4bac-8e7b-44bb6b293678)

**Comment by jtgans** [comment]
Why what? Can you say more?

**Comment by polluks** [comment]
`bload` does not work as expected, see line zero (I suppose some pointers are wrong with your footer `sys`). However you can use this command to load tanks :)

**Comment by jtgans** [comment]
Yeah, BLOAD is not intended to be used to load applications. It's to be used for loading files that were BSAVE'd to disk to provide a sane way to store sprite data and stuff like that that needs to be loaded at specific addresses and banks. I wrote that header expecting it to be LOAD'ed or DLOAD'ed, not BLOAD'ed.
